version: '3.6'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: dockerfiles/nginx/Dockerfile
    restart: always
    volumes:
      - /var/log/nginx:/var/log/nginx
      - ./dockerfiles/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dockerfiles/nginx/conf.d:/etc/nginx/conf.d
#      - ./public/bundles/:/var/www/public/bundles
    ports:
      - '8810:80'
    depends_on:
      - php-fpm
    networks:
      application:

  php-fpm:
    container_name: php-fpm
    build:
      dockerfile: dockerfiles/php-fpm/Dockerfile
      context: .
    restart: always
    environment:
      PHP_MEMORY_LIMIT: "2048M"
      XDEBUG_CONFIG: client_host=host.docker.internal idekey=admin-board-docker log_level=0
      XDEBUG_MODE: "coverage,develop,debug"
    volumes:
      - ./:/var/www:delegated
    expose:
      - '9000'
    networks:
      application:

  postgres:
    build:
      context: .
      dockerfile: dockerfiles/db/Dockerfile
    container_name: postgres
    ports:
      - "6432:5432"
    volumes:
      - ./volumes/db:/var/lib/postgresql/data:delegated
    command: [ "postgres", "-c", "log_statement=all" ]
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: app
    networks:
      application:


networks:
  application:
    name: application
    driver: bridge
