version: '3.6'

services:
  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx/Dockerfile
    restart: always
    volumes:
      - /var/log/nginx:/var/log/nginx
      - ./dockerfiles/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dockerfiles/nginx/conf.d:/etc/nginx/conf.d
#      - ./public/bundles/:/var/www/public/bundles
    ports:
      - '8810:80'
    depends_on:
      - php-fpm
    networks:
      application:

  php-fpm:
    container_name: admin-board_php-fpm
    image: registry.bank131.ru/131/dev-tools/php/8.1-dev:2.1.1
    restart: always
    environment:
      PHP_MEMORY_LIMIT: "2048M"
      XDEBUG_CONFIG: client_host=10.254.254.254 idekey=admin-board-docker
      XDEBUG_MODE: "coverage,develop,debug"
    volumes:
        - ./:/var/www/
    expose:
      - '9000'
    networks:
      application:

  postgres:
    build:
      context: .
      dockerfile: dockerfiles/db/Dockerfile
    container_name: postgres
    ports:
      - "6432:5432"
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    command: [ "postgres", "-c", "log_statement=all" ]
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: app
    networks:
      application:


networks:
  application:
    name: application
    driver: bridge
