Knp\Component\Pager\Pagination\AbstractPagination:
    exclusion_policy: ALL
    properties:
        items:
            expose: true
            access_type: public_methoddock
            accessor:
                getter: getItems
            type: array
            serialized_name: data
        currentPageNumber:
            expose: true
            serialized_name: currentPage
        numItemsPerPage:
            expose: true
            serialized_name: itemCountOnPage
        totalCount:
            expose: true
            serialized_name: totalItemCount