monolog:
    handlers:
        stdout:
            type: stream
            handler: FilterHandler
            formatter: "monolog.formatter.json"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
