monolog:
    handlers:
        stdout:
            type: stream
            handler: FilterHandler
            formatter: "monolog.formatter.json"
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
